frontend:
	@echo Installing Frontend
cart:
	@echo Installing cart
catalogue:
	@echo Installing catalogue
mongo:
	@echo Installing mongo
mysql:
	@echo Installing mysql
payment:
	@echo Installing payment
rabbitmq:
	@echo Installing rabbitmq
redis:
	@echo Installing redis
shipping:
	@echo Installing shipping
user:
	@echo Installing user