help:      ##print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:  ## Install frontend Component
	@echo Installing Frontend
cart:	   ## Install cart Component
	@echo Installing cart
catalogue: ## Install catalogue Component
	@echo Installing catalogue
mongo:     ## Install mongo Component
	@echo Installing mongo
mysql:     ## Install mysql Component
	@echo Installing mysql
payment:   ## Install payment Component
	@echo Installing payment
rabbitmq:  ## Install rabbitmq Component
	@echo Installing rabbitmq
redis:     ## Install redis Component
	@echo Installing redis
shipping:  ## Install shipping Component
	@echo Installing shipping
user:      ## Install user Component
	@echo Installing user